routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//tipos de rutas -- get,post,put,delete.

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Pràctica de rutas, practica de get que devuelva hola mundo

Route::get('/saludos', function (){
    return "Hola Mundo";
});

Route::get('/mensaje/{nombre}/{apellido}/{id}', function($nombre,$apellido,$id){
    return "los datos ingresados: <br/>$nombre, <br/>$apellido, <br/>$id";
});

//ruta con parametros de vueltos y no devueltos
Route::get('/potencia/{base?}/{exponente?}', function($base=2,$exponente=2){
    return pow($base,$exponente);
});

//Filtrar rutas
Route::get('/numero/{id}', function($id){
    return pow($id, 2);
})->where(['id'=>'[0-9]+']);

Route::get('/numero/{id}/{id2}', function($id,$id2){
    return pow(3, $id);
})->where(['id'=>'[0-9]+','id2'=>'[5]+']);

Route::get('/slug/{accion}/{num}', function($accion,$num){
    switch ($accion) {
        case 'potencia':
            return pow(3, $num);
            break;
        
        case 'suma':
            return 4+$num;
            break;
    } 
})->where(['num'=>'[0-9]+','accion'=>'potencia|suma']);

Route::group(['prefix'=>'filtros'], function(){
    Route::get('/datos/{id}', function($id){
        return "numero $id";
    })->where(['id'=>'[0-9]+']);

    Route::get('/datos/{id}', function($id){
        return "Hola Mundo";
    })->where(['id'=>'hola']);

    Route::get('/datos/{id}', function($id){
        return "hola tu parametro fue: $id";
    })->where(['id'=>'[-\w]+'])->name('numero');
});

Route::get('/hora', function(){
    return date('Y-m-d H:i:s');
})->name('Hora');

Route::get('/saludo', 'PruebaController@getSaludo')->name('saludo');

Route::get('/saludo_concatenado_upper/{palabra}', 'PruebaController@getSaludo_concatenado_upper')->name('saludo');

//Resource para todo los mètodos

Route::resource('resource','ResourceController');

//Resource exclusivo
/*Route::resource('resource','ResourceController',['only'=>'index']);*/

//Resource todos menos uno
Route::resource('resource','ResourceController',['except'=>'index']);

Route::get('vista-simple','PruebaController@getVista')->name('vistasimple');

        /*                               *\
                INICIO DEL PROYECTO
        \*                               */

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::group pertenecen a mismo grupo
Route::group(['middleware' => ['auth'],'prefix'=>'admin', 'as'=>'admin.'], function(){
    //atachar un controlador a un modelo especìfico
    Route::resource('role','Cruds\RoleController');
    Route::resource('category','Cruds\CategoryController');
});

Route::group(['middleware' => ['auth'],'prefix'=>'articles', 'as'=>'articles.'], function(){
    //atachar un controlador a un modelo especìfico
    Route::resource('book','BookController');
    Route::get('book-datatable','BookController@datatable');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\softDeletes;

class Category extends Model
{
    //trait de programacion, especie de abstraccion
    use softDeletes;

    protected $connection = 'mysql';
    protected $table      = 'categories';

    protected $fillable = [
        'name', 'description'
    ];

    //relaciones
    public function books(){
        return $this->hasMany(Book::class,'category_id','id');
    }
}

app/Http/Controllers/Cruds/CategoryController.php
<?php

namespace App\Http\Controllers\Cruds;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use Facades\App\Facades\AlertManager;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $arrCategories=Category::orderBy('name','asc')->where('name','like',"%$request->scope%")->paginate(2);
        return view('cruds.category.index')->with(['categories'=>$arrCategories,'scope'=>$request->scope ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cruds.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|min:3|max:50|string|unique:categories,name',
            'description'=>"required|min:3|max:50|string"
        ]);


        $objCategory = new Category();
        /*$objCategory->name = $request->name;
        $objCategory->description = $request->description;*/
        $objCategory->fill($request->all());
        $objCategory->save();
        AlertManager::success('Registro guardado correctamente');
        return redirect()->route('admin.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //return view('cruds.category.show',compact(['category']))
        return view('cruds.category.show')->with(['category'=>$category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /*public function edit($id)
    {
        $category=Category::findOrFail($id);
        dd($category);
    }*/
    public function edit(Category $category)
    {
        //return view('cruds.category.edit',compact(['category']));
        return view('cruds.category.edit')->with(['category'=>$category]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request,[
            'name'=>"required|min:3|max:50|string|unique:categories,name,{$category->id},id",
            'description'=>"required|min:3|max:50|string"
        ]);
        $category->fill($request->all());
        $category->save();
        AlertManager::success('Registro actualizado correctamente');
        return redirect()->route('admin.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        AlertManager::success('Registro eliminado  correctamente');
        return redirect()->route('admin.category.index');
    }
}

app/Http/Controllers/Cruds/RoleController.php
<?php

namespace App\Http\Controllers\Cruds;

use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Facades\App\Facades\AlertManager;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $arrRoles=Role::orderBy('name','asc')->where('name','like',"%$request->scope%")->paginate(2);
        return view('cruds.role.index')->with(['roles'=>$arrRoles,'scope'=>$request->scope ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cruds.role.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|min:3|max:50|string|unique:roles,name',
            'description'=>"required|min:3|max:50|string"
        ]);

        $objRole = new Role();
        /*$objRole->name = $request->name;
        $objRole->description = $request->description;*/
        $objRole->fill($request->all());
        $objRole->save();
        AlertManager::success('Registro guardado correctamente');
        return redirect()->route('admin.role.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //return view('cruds.role.show',compact(['role']))
        return view('cruds.role.show')->with(['role'=>$role]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    /*public function edit($id)
    {
        $role=Role::findOrFail($id);
        dd($role);
    }*/
    public function edit(Role $role)
    {
        //return view('cruds.role.edit',compact(['role']));
        return view('cruds.role.edit')->with(['role'=>$role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request,[
            'name'=>"required|min:3|max:50|string|unique:categories,name,{$role->id},id",
            'description'=>"required|min:3|max:50|string"
        ]);
        $role->fill($request->all());
        $role->save();
        AlertManager::success('Registro actualizado correctamente');
        return redirect()->route('admin.role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        AlertManager::success('Registro eliminado  correctamente');
        return redirect()->route('admin.role.index');
    }
}

resources/views/cruds/category/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="card">
                <div class="card-header">Crear Categoría</div>
                <div class="card-body">
                    {!! Form::open(['route'=>'admin.category.store']) !!}

                        @component('components.crudbasic')
                            @slot('name',)
                            @slot('description',)
                            @slot('parameters',[])
                        @endcomponent

                        {!! Form::submit('Guardar',['class'=>'btn btn-success btn-xs']) !!}
                        {{ link_to_route('admin.category.index','REGRESAR',[],['class'=>'btn btn-warning btn-xs']) }}
                        
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cruds/category/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="card">
                <div class="card-header">Editar Categoría</div>
                <div class="card-body">
                    {!! Form::open(['route'=>['admin.category.update',$category],'method'=>'PUT']) !!}
                    
                        @component('components.crudbasic')
                            @slot('name',$category->name)
                            @slot('description',$category->description)
                            @slot('parameters',[])
                        @endcomponent

                        {!! Form::submit('Guardar',['class'=>'btn btn-success btn-xs']) !!}
                        {{ link_to_route('admin.category.index','REGRESAR',[],['class'=>'btn btn-warning btn-xs']) }}

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cruds/category/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="card">
                <div class="card-header">Listado Categoría</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <a class="btn btn-primary btn-xs" href="{{ route('admin.category.create') }}">CREAR</a>
                        </div>
                        <div class="col-md-4">
                        {!! Form::open(['route'=>'admin.category.index','method'=>'GET']) !!}
                            {!! Form::text('scope',$scope,['class'=>'form-control']) !!}
                            {!! Form::submit('Buscar',['class'=>'btn btn-success btn-xs'])!!}
                        {!! Form::close() !!}
                        </div>
                    </div>
                    <table class="table">
                        <thead>
                            <th>Id</th>
                            <th>Código</th>
                            <th>Descripción</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->description }}</td>
                                    <td>
                                        <table>
                                            <tr>
                                                <td class="p-1">
                                                    {{ link_to_route('admin.category.edit','EDT',[$category->id],['class'=>'btn btn-warning btn-xs']) }}
                                                </td>
                                                <td class="p-1">
                                                    {{ link_to_route('admin.category.show','VER',[$category->id],['class'=>'btn btn-primary btn-xs']) }}
                                                </td>
                                                <td class="p-1">
                                                    {!! Form::open(['route'=>['admin.category.destroy',$category->id],'method'=>'DELETE']) !!}
                                                        {!! Form::submit('DEL',['class'=>'btn btn-danger btn-xs']) !!}
                                                    {!! Form::close() !!}
                                                </td>
                                            </tr>
                                        </table>
                                        
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {!! $categories->render() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cruds/category/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="card">
                <div class="card-header">Vista Categoría</div>
                <div class="card-body">

                    @component('components.crudbasic')
                        @slot('name',$category->name)
                        @slot('description',$category->description)
                        @slot('parameters',['readonly','readonly'])
                    @endcomponent
                
                        {{ link_to_route('admin.category.index','REGRESAR',[],['class'=>'btn btn-warning btn-xs']) }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection