routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//tipos de rutas -- get,post,put,delete.

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Pràctica de rutas, practica de get que devuelva hola mundo

Route::get('/saludos', function (){
    return "Hola Mundo";
});

Route::get('/mensaje/{nombre}/{apellido}/{id}', function($nombre,$apellido,$id){
    return "los datos ingresados: <br/>$nombre, <br/>$apellido, <br/>$id";
});

//ruta con parametros de vueltos y no devueltos
Route::get('/potencia/{base?}/{exponente?}', function($base=2,$exponente=2){
    return pow($base,$exponente);
});

//Filtrar rutas
Route::get('/numero/{id}', function($id){
    return pow($id, 2);
})->where(['id'=>'[0-9]+']);

Route::get('/numero/{id}/{id2}', function($id,$id2){
    return pow(3, $id);
})->where(['id'=>'[0-9]+','id2'=>'[5]+']);

Route::get('/slug/{accion}/{num}', function($accion,$num){
    switch ($accion) {
        case 'potencia':
            return pow(3, $num);
            break;
        
        case 'suma':
            return 4+$num;
            break;
    } 
})->where(['num'=>'[0-9]+','accion'=>'potencia|suma']);

Route::group(['prefix'=>'filtros'], function(){
    Route::get('/datos/{id}', function($id){
        return "numero $id";
    })->where(['id'=>'[0-9]+']);

    Route::get('/datos/{id}', function($id){
        return "Hola Mundo";
    })->where(['id'=>'hola']);

    Route::get('/datos/{id}', function($id){
        return "hola tu parametro fue: $id";
    })->where(['id'=>'[-\w]+'])->name('numero');
});

Route::get('/hora', function(){
    return date('Y-m-d H:i:s');
})->name('Hora');

Route::get('/saludo', 'PruebaController@getSaludo')->name('saludo');

Route::get('/saludo_concatenado_upper/{palabra}', 'PruebaController@getSaludo_concatenado_upper')->name('saludo');

//Resource para todo los mètodos

Route::resource('resource','ResourceController');

//Resource exclusivo
/*Route::resource('resource','ResourceController',['only'=>'index']);*/

//Resource todos menos uno
Route::resource('resource','ResourceController',['except'=>'index']);

Route::get('vista-simple','PruebaController@getVista')->name('vistasimple');

        /*                               *\
                INICIO DEL PROYECTO
        \*                               */

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

//Route::group pertenecen a mismo grupo
Route::group(['middleware' => ['auth'],'prefix'=>'admin', 'as'=>'admin.'], function(){
    //atachar un controlador a un modelo especìfico
    Route::resource('role','Cruds\RoleController');
    Route::resource('category','Cruds\CategoryController');
});

Route::group(['middleware' => ['auth'],'prefix'=>'articles', 'as'=>'articles.'], function(){
    //atachar un controlador a un modelo especìfico
    Route::resource('book','BookController');
    Route::get('book-datatable','BookController@datatable');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="/css/fileinput.min.css" rel="stylesheet">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css">

        <!-- Scripts -->
        
        <!--script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script-->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
        <script src="/js/fileinput.min.js"></script>
        @yield('js')
        <!--script src="{{ asset('js/app.js') }}" defer></script--->
        <script src="/js/util.js"></script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto float-right">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.role.index') }}">Roles</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.category.index') }}">Categorías</a>
                            </li>
                            <li class="nav-item">
                                    <a class="nav-link" href="{{ route('articles.book.index') }}">Libros</a>
                            </li>
                            <li class="nav-item dropdown float-left">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">

            {!! AlertManager::render() !!}
            @yield('datatable')
            @yield('content')
            
    
        </main>
    </div>
        </body>
</html>